language: generic
sudo: false

env:
  global:
    BYOND_MAJOR="511"
    BYOND_MINOR="1385"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - mkdir -p "$HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}"
  - cd "$HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}"
  - curl "http://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${BYOND_MINOR}_byond_linux.zip" -o byond.zip
  - unzip byond.zip
  - cd byond
  - make here

script:
  - (! grep 'step_[xy]' maps/**/*.dmm))
  - cd ..
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - dm.sh baystation12.dme
  - grep ", 0 warnings" build_log.txt
  - DreamDaemon baystation12.dmb -invisible -trusted -core 2>&1 | tee log.txt
  - grep "All Unit Tests Passed" log.txt
  - grep "Caught 0 Runtimes" log.txt
  - (! grep "runtime error:" log.txt)
  - (! grep 'Process scheduler caught exception processing' log.txt)
  - (! grep "WARNING:" log.txt)
  - (! grep "ERROR:" log.txt)
